# Use official Node.js runtime as a base image
FROM node:16

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose port 5000 (or the port your app uses)
EXPOSE 5000

# Define the command to run your app
CMD ["node", "app.js"]
